projects/anglify/src/modules/tooltip/tooltip.directive.ts

Implement tooltipCloseDelay property

---

projects/anglify/src/modules/tooltip/index.scss
projects/anglify/src/modules/tooltip/tooltip.directive.ts
projects/docs/src/app/examples/tooltip/show-hide-manually/show-hide-manually.component.html
projects/docs/src/app/examples/tooltip/show-hide-manually/show-hide-manually.component.scss
projects/docs/src/app/examples/tooltip/show-hide-manually/show-hide-manually.component.ts
projects/docs/src/app/examples/tooltip/tooltip-examples.module.ts
projects/docs/src/app/pages/component-pages/tooltip-page/tooltip-page.component.html

Add possibility to open and close tooltips manually

---

projects/anglify/src/modules/tooltip/tooltip.directive.ts

Open tooltip when the host element gets focused

---

projects/anglify/src/modules/tooltip/tooltip.directive.ts
projects/docs/src/app/examples/tooltip/custom-mounting-point/custom-mounting-point.component.html
projects/docs/src/app/examples/tooltip/custom-mounting-point/custom-mounting-point.component.scss
projects/docs/src/app/examples/tooltip/custom-mounting-point/custom-mounting-point.component.ts
projects/docs/src/app/examples/tooltip/tooltip-examples.module.ts
projects/docs/src/app/pages/component-pages/tooltip-page/tooltip-page.component.html

Allow mounting the tooltip at any location by using a property

---

projects/anglify/src/modules/overlay/overlay.directive.ts
projects/anglify/src/modules/stepper/components/stepper-header/stepper-header.component.scss
projects/anglify/src/modules/stepper/stepper.module.ts
projects/docs/src/app/examples/stepper/horizontal-stepper/horizontal-stepper.component.html
projects/docs/src/app/examples/stepper/horizontal-stepper/horizontal-stepper.component.scss
projects/docs/src/app/examples/stepper/stepper-examples.module.ts
projects/docs/src/app/examples/stepper/vertical-stepper/vertical-stepper.component.html
projects/docs/src/app/examples/stepper/vertical-stepper/vertical-stepper.component.scss

Add overlay support to stepper headers

---

projects/anglify/src/modules/tooltip/tooltip.directive.ts

Position tooltips with dynamic content correctly

---

projects/anglify/src/modules/tooltip/tooltip-settings.token.ts
projects/anglify/src/modules/tooltip/tooltip.directive.ts
projects/anglify/src/modules/tooltip/tooltip.interface.ts
projects/anglify/src/modules/tooltip/tooltip.module.ts
projects/anglify/src/public-api.ts
projects/docs/src/app/examples/tooltip/tooltip-examples.module.ts

Add possibility to globally overwrite the default tooltip values

---

projects/anglify/src/modules/tooltip/tooltip-settings.token.ts
projects/anglify/src/modules/tooltip/tooltip.directive.ts
projects/anglify/src/modules/tooltip/tooltip.module.ts
projects/docs/src/app/app.module.ts

Fix global tooltip settings provider

---

projects/anglify/src/modules/list/components/list-item-description/list-item-description.component.html
projects/anglify/src/modules/list/components/list-item-description/list-item-description.component.scss
projects/anglify/src/modules/list/components/list-item-description/list-item-description.component.ts
projects/anglify/src/modules/list/components/list-item-title/list-item-title.component.html
projects/anglify/src/modules/list/components/list-item-title/list-item-title.component.scss
projects/anglify/src/modules/list/components/list-item-title/list-item-title.component.ts
projects/anglify/src/modules/list/components/list-item/list-item.component.html
projects/anglify/src/modules/list/components/list-item/list-item.component.scss
projects/anglify/src/modules/list/components/list-item/list-item.component.ts
projects/anglify/src/modules/list/components/list/list.component.html
projects/anglify/src/modules/list/components/list/list.component.ts
projects/anglify/src/modules/list/directives/append/append.directive.ts
projects/anglify/src/modules/list/directives/prepend/prepend.directive.ts
projects/anglify/src/modules/list/list.module.ts
projects/anglify/src/modules/overlay/overlay.directive.ts
projects/anglify/src/styles/settings/typography.scss
projects/docs/src/app/app-routing.module.ts
projects/docs/src/app/app.module.ts
projects/docs/src/app/pages/component-pages/list-page/list-page.component.html
projects/docs/src/app/pages/component-pages/list-page/list-page.component.ts
projects/docs/src/app/pages/home/home.component.ts

feature(list): Implement list component

---

projects/anglify/src/modules/card/_variables.scss
projects/anglify/src/modules/card/card-settings.token.ts
projects/anglify/src/modules/card/card.component.html
projects/anglify/src/modules/card/card.component.scss
projects/anglify/src/modules/card/card.component.ts
projects/anglify/src/modules/card/card.interface.ts
projects/anglify/src/modules/card/card.module.ts
projects/docs/src/app/app-routing.module.ts
projects/docs/src/app/app.module.ts
projects/docs/src/app/pages/component-pages/card-page/card-page.component.html
projects/docs/src/app/pages/component-pages/card-page/card-page.component.ts
projects/docs/src/app/pages/home/home.component.html
projects/docs/src/app/pages/home/home.component.scss
projects/docs/src/app/pages/home/home.component.ts

feature(card): Implement card component

---

.vscode/extensions.json
.vscode/settings.json
projects/anglify/ng-package.json
projects/anglify/src/modules/progress-circular/_variables.scss
projects/anglify/src/modules/progress-circular/progress-circular-settings.token.ts
projects/anglify/src/modules/progress-circular/progress-circular.component.html
projects/anglify/src/modules/progress-circular/progress-circular.component.scss
projects/anglify/src/modules/progress-circular/progress-circular.component.ts
projects/anglify/src/modules/progress-circular/progress-circular.interface.ts
projects/anglify/src/modules/progress-circular/progress-circular.module.ts
projects/anglify/src/public-api.ts
projects/docs/src/app/app-routing.module.ts
projects/docs/src/app/app.module.ts
projects/docs/src/app/examples/progress-circular/indeterminate/indeterminate.component.html
projects/docs/src/app/examples/progress-circular/indeterminate/indeterminate.component.ts
projects/docs/src/app/examples/progress-circular/progress-circular-examples.module.ts
projects/docs/src/app/examples/progress-circular/rotation/rotation.component.html
projects/docs/src/app/examples/progress-circular/rotation/rotation.component.ts
projects/docs/src/app/examples/progress-circular/show-progress/show-progress.component.html
projects/docs/src/app/examples/progress-circular/show-progress/show-progress.component.ts
projects/docs/src/app/pages/component-pages/progress-circular-page/progress-circular-page.component.html
projects/docs/src/app/pages/component-pages/progress-circular-page/progress-circular-page.component.ts
projects/docs/src/app/pages/home/home.component.ts

Progress circular component

---

apps/docs/src/app/app.module.ts
apps/docs/src/app/examples/menu/menu-examples.module.ts
apps/docs/src/app/examples/menu/show-hide-manually/show-hide-manually.component.html
apps/docs/src/app/examples/menu/show-hide-manually/show-hide-manually.component.scss
apps/docs/src/app/examples/menu/show-hide-manually/show-hide-manually.component.ts
apps/docs/src/app/pages/component-pages/menu-page/menu-page.component.html
libs/anglify/src/modules/menu/menu.directive.ts
libs/anglify/src/modules/menu/menu.interface.ts

add: Possibility to control menus manually (open, close, toggle)

---

libs/anglify/src/composables/position/position.interface.ts
libs/anglify/src/composables/position/position.service.ts
libs/anglify/src/modules/checkbox/interfaces/checkbox.interface.ts
libs/anglify/src/modules/list/components/list-item/list-item.component.ts
libs/anglify/src/modules/menu/components/menu/menu.component.ts
libs/anglify/src/modules/menu/menu-settings.token.ts
libs/anglify/src/modules/menu/menu.directive.ts
libs/anglify/src/modules/menu/menu.interface.ts
libs/anglify/src/modules/stepper/components/stepper-header/stepper-header.component.ts
libs/anglify/src/modules/stepper/components/stepper/stepper.component.ts
libs/anglify/src/modules/stepper/directives/step/step.directive.ts
libs/anglify/src/modules/tooltip/components/tooltip/tooltip.component.ts
libs/anglify/src/modules/tooltip/tooltip-settings.token.ts
libs/anglify/src/modules/tooltip/tooltip.directive.ts
libs/anglify/src/modules/tooltip/tooltip.interface.ts
package-lock.json
package.json

This introduces a super tiny 600b library (https://floating-ui.com) to handle the calculation of the positioning of elements that should float.
This should eliminate all bugs we currently have regarding this.

refactor: rewrite position service to use floating-ui lib

---

.github/ISSUE_TEMPLATE/bug.yml
.github/PULL_REQUEST_TEMPLATE.md

chore: improve pull request and issue templates

---

apps/docs/src/app/examples/nav-drawer/modal-drawer/modal-drawer.component.ts
libs/anglify/src/composables/elevation/elevation.service.ts
libs/anglify/src/composables/ripple/ripple.service.spec.ts
libs/anglify/src/mocks/renderer2.mock.ts
libs/anglify/src/modules/button/button.component.ts
libs/anglify/src/modules/card/card.component.ts
libs/anglify/src/modules/checkbox/checkbox.component.spec.ts
libs/anglify/src/modules/checkbox/checkbox.component.ts
libs/anglify/src/modules/checkbox/functions/register-icons.function.ts
libs/anglify/src/modules/common/directives/slot-outlet/slot-outlet.directive.ts
libs/anglify/src/modules/common/directives/slot/slot.directive.spec.ts
libs/anglify/src/modules/common/directives/slot/slot.directive.ts
libs/anglify/src/modules/common/pipes/boolean-like-to-boolean/boolean-like-to-boolean.pipe.ts
libs/anglify/src/modules/common/pipes/clamp/clamp.pipe.spec.ts
libs/anglify/src/modules/common/pipes/clamp/clamp.pipe.ts
libs/anglify/src/modules/common/pipes/find-slot/find-slot.pipe.ts
libs/anglify/src/modules/common/pipes/percent/percent.pipe.spec.ts
libs/anglify/src/modules/common/pipes/percent/percent.pipe.ts
libs/anglify/src/modules/list/components/list-item-group/list-item-group.component.ts
libs/anglify/src/modules/list/components/list/list.component.ts
libs/anglify/src/modules/menu/menu.directive.ts
libs/anglify/src/modules/nav-drawer/nav-drawer.component.ts
libs/anglify/src/modules/progress-circular/progress-circular.component.ts
libs/anglify/src/modules/radio-button/radio-button.component.ts
libs/anglify/src/modules/tooltip/tooltip.directive.ts
libs/anglify/src/utils/functions.ts

style: cleanup return types, add missing spacing

---

libs/anglify/src/styles/settings/typography.scss

feat: typographies should not have predefined colors

---

.husky/commit-msg
.husky/pre-commit
package-lock.json
package.json

build: add husky pre-commit checks

---

apps/docs/src/app/examples/form-field/disabled-validation/disabled-validation.component.html
apps/docs/src/app/examples/form-field/disabled-validation/disabled-validation.component.ts
apps/docs/src/app/examples/form-field/form-field-examples.module.ts
apps/docs/src/app/examples/form-field/server-error-handling/server-error-handling.component.html
apps/docs/src/app/examples/form-field/server-error-handling/server-error-handling.component.ts
libs/anglify/src/modules/form-field/directives/input.directive.ts
libs/anglify/src/modules/form-field/form-field.component.ts

fix: form field error state checking

---

libs/anglify/src/modules/bottom-navigation/_variables.scss
libs/anglify/src/modules/button/_variables.scss
libs/anglify/src/modules/toolbar/_variables.scss
libs/anglify/src/styles/themes/dark.scss
libs/anglify/src/styles/themes/light.scss

feat: dark theme colors for bars

---

apps/docs/src/app/app-routing.module.ts
apps/docs/src/app/app.component.ts
apps/docs/src/app/app.module.ts
apps/docs/src/app/examples/snackbar/configuration/configuration.component.html
apps/docs/src/app/examples/snackbar/configuration/configuration.component.ts
apps/docs/src/app/examples/snackbar/snackbar-examples.module.ts
apps/docs/src/app/pages/component-pages/dialog-page/dialog-page.component.html
apps/docs/src/app/pages/component-pages/snackbar-page/snackbar-page.component.html
apps/docs/src/app/pages/component-pages/snackbar-page/snackbar-page.component.ts
libs/anglify/src/index.ts
libs/anglify/src/modules/snackbar/_variables.scss
libs/anglify/src/modules/snackbar/snackbar-settings.token.ts
libs/anglify/src/modules/snackbar/snackbar.component.html
libs/anglify/src/modules/snackbar/snackbar.component.scss
libs/anglify/src/modules/snackbar/snackbar.component.ts
libs/anglify/src/modules/snackbar/snackbar.interface.ts
libs/anglify/src/modules/snackbar/snackbar.module.ts
libs/anglify/src/modules/snackbar/snackbar.service.ts
package-lock.json
package.json

feat: snackbar

---

apps/docs/src/app/app.component.html
libs/anglify/src/modules/list/components/list-group/list-group.component.ts

151 feat nav drawer subroutes

---

libs/anglify/src/modules/progress-linear/progress-linear-settings.token.ts
libs/anglify/src/modules/progress-linear/progress-linear.component.ts
libs/anglify/src/modules/progress-linear/progress-linear.interface.ts

refactor: add settingstoken for progress linear

---

libs/anglify/src/modules/progress-linear/progress-linear.interface.ts
libs/anglify/src/modules/toolbar/toolbar-settings.token.ts
libs/anglify/src/modules/toolbar/toolbar.component.ts
libs/anglify/src/modules/toolbar/toolbar.interface.ts

refactor(Toolbar): remove unused navigation input property

---

libs/anglify/src/modules/list/_variables.scss
libs/anglify/src/modules/list/components/list-item/list-item.component.scss

feat(ListItem): active text color

---

libs/anglify/src/modules/badge/badge.component.scss

fix(Badge): Badge border radius

---

libs/anglify/src/composables/ripple/ripple.service.ts

fix(Ripple): Origin fix

---

libs/anglify/src/modules/list/components/list-group/list-group.component.ts

refactor: check router url for include, not for the exacte route url

---

libs/anglify/src/modules/dialog/dialog.component.html
libs/anglify/src/modules/dialog/dialog.component.scss
libs/anglify/src/modules/dialog/dialog.component.ts
libs/anglify/src/modules/dialog/dialog.service.ts
libs/anglify/src/modules/snackbar/snackbar.service.ts
libs/anglify/src/styles/index.scss

refactor: dialog and snackbar service simplifications

---

libs/anglify/src/modules/dialog/dialog.service.ts
libs/anglify/src/modules/snackbar/snackbar.component.ts
libs/anglify/src/modules/snackbar/snackbar.interface.ts
libs/anglify/src/modules/snackbar/snackbar.service.ts

fix: detaching dialog and snackbars properly

---

apps/docs/src/app/examples/tooltip/custom-mounting-point/custom-mounting-point.component.html
apps/docs/src/app/examples/tooltip/custom-mounting-point/custom-mounting-point.component.ts
apps/docs/src/app/examples/tooltip/delay/delay.component.html
apps/docs/src/app/examples/tooltip/different-positions/different-positions.component.html
libs/anglify/src/modules/tooltip/tooltip-settings.token.ts
libs/anglify/src/modules/tooltip/tooltip.directive.ts
libs/anglify/src/modules/tooltip/tooltip.interface.ts

refactor(Tooltip): add Input Tooltipconfig #149

---

libs/anglify/src/modules/radio-button/radio-button.component.scss

fix(Radio Button): hover state when hovering over label #154

---

libs/anglify/src/modules/dialog/_variables.scss
libs/anglify/src/modules/dialog/dialog.component.scss
libs/anglify/src/modules/dialog/dialog.service.ts

fix(dialog): backdrop clicking reason and pane class

---

apps/docs/src/app/examples/breadcrumbs/basic/basic.component.html
apps/docs/src/app/examples/breadcrumbs/basic/basic.component.ts
apps/docs/src/app/examples/breadcrumbs/breadcrumbs-example.module.ts
apps/docs/src/app/examples/breadcrumbs/icon/icon.component.html
apps/docs/src/app/examples/breadcrumbs/icon/icon.component.ts
apps/docs/src/app/layouts/default/default.component.ts
apps/docs/src/app/pages/components/breadcrumbs-page/breadcrumbs-page.component.html
apps/docs/src/app/pages/components/breadcrumbs-page/breadcrumbs-page.component.ts
apps/docs/src/app/pages/components/components-routing.module.ts
apps/docs/src/app/pages/components/components.module.ts
libs/anglify/ng-package.json
libs/anglify/src/index.ts
libs/anglify/src/modules/breadcrumbs/_variables.scss
libs/anglify/src/modules/breadcrumbs/breadcrumbs-settings.token.ts
libs/anglify/src/modules/breadcrumbs/breadcrumbs.component.html
libs/anglify/src/modules/breadcrumbs/breadcrumbs.component.scss
libs/anglify/src/modules/breadcrumbs/breadcrumbs.component.spec.ts
libs/anglify/src/modules/breadcrumbs/breadcrumbs.component.ts
libs/anglify/src/modules/breadcrumbs/breadcrumbs.interface.ts
libs/anglify/src/modules/breadcrumbs/breadcrumbs.module.ts

feat(Breadcrumbs): implement Breadcrumbs

---

libs/anglify/src/modules/dialog/dialog-context.interface.ts
libs/anglify/src/modules/dialog/dialog.component.ts
libs/anglify/src/modules/dialog/dialog.service.ts
libs/anglify/src/modules/snackbar/snackbar.component.ts
libs/anglify/src/modules/snackbar/snackbar.interface.ts
libs/anglify/src/modules/snackbar/snackbar.service.ts

refactor(completeWith): modal data and snackbar data format

---

libs/anglify/src/modules/dialog/dialog-context.interface.ts
libs/anglify/src/modules/snackbar/snackbar.interface.ts

fix: expose modal data and snackbar data generic to allow typing the return data

---

apps/docs/src/app/examples/dialog/simple/simple.component.ts
apps/docs/src/app/examples/snackbar/basic/basic.component.ts
apps/docs/src/app/examples/snackbar/indefinitely/indefinitely.component.ts
apps/docs/src/app/pages/components/dialog-page/dialog-page.component.html
apps/docs/src/app/pages/components/snackbar-page/snackbar-page.component.html
libs/anglify/src/modules/dialog/dialog.service.ts
libs/anglify/src/modules/snackbar/snackbar.service.ts

feat(Dialog, Snackbar): simple opening method

---

apps/docs/src/app/examples/text-area/autoresize/autoresize.component.html
apps/docs/src/app/examples/text-area/autoresize/autoresize.component.scss
apps/docs/src/app/examples/text-area/autoresize/autoresize.component.ts
apps/docs/src/app/examples/text-area/text-area-examples.module.ts
apps/docs/src/app/pages/components/text-area-page/text-area-page.component.html
libs/anglify/src/modules/input/input.directive.ts
libs/anglify/src/styles/index.scss

feat(Textarea): autoresize

---

libs/anglify/src/modules/input/_details.scss
libs/anglify/src/modules/input/input.component.html
libs/anglify/src/modules/input/input.component.spec.ts
libs/anglify/src/modules/input/input.component.ts
libs/anglify/src/modules/input/input.module.ts
libs/anglify/src/modules/text-area/text-area.component.spec.ts
libs/anglify/src/modules/text-area/text-area.component.ts
libs/anglify/src/modules/text-field/text-field.component.spec.ts
libs/anglify/src/modules/text-field/text-field.component.ts
libs/anglify/src/modules/tooltip/tooltip-settings.token.ts
libs/anglify/src/modules/tooltip/tooltip.directive.ts
libs/anglify/src/modules/tooltip/tooltip.interface.ts
libs/anglify/tsconfig.spec.json

feat(InputComponent): show tooltip when hint is cut off

---

libs/anglify/src/test-setup.ts
package-lock.json
package.json

feat: testing-library

---

libs/anglify/src/components/combobox/combobox.component.ts
libs/anglify/src/components/select/select.component.ts

fix: select/autocomplete/combobox this binding bug

---

libs/anglify/src/components/list/_variables.scss
libs/anglify/src/components/list/components/list-item/list-item.component.scss

fix(ListItem): change ListItem gap to match material standards

---

apps/docs/src/app/components/code-example/code-example.component.scss
apps/docs/src/app/components/code-example/code-example.component.ts

docs: allow overflow inside code examples

---

libs/anglify/src/composables/ripple/ripple.service.ts

fix(Ripple): ripples now get removed on blur events

---

libs/anglify/src/components/list/components/list-item/list-item.component.ts

feat(ListItem): list items are now keyboard focusable by default

---

apps/docs/src/app/examples/badge/visibility/visibility.component.html
apps/docs/src/app/examples/badge/visibility/visibility.component.ts
apps/docs/src/app/examples/checkbox/appearances/appearances.component.html
apps/docs/src/app/examples/checkbox/indeterminate/indeterminate.component.html
apps/docs/src/app/examples/checkbox/indeterminate/indeterminate.component.scss
apps/docs/src/app/examples/checkbox/indeterminate/indeterminate.component.ts
apps/docs/src/app/examples/checkbox/sizes/sizes.component.html
apps/docs/src/app/examples/data-table/selectable-rows/selectable-rows.component.html
apps/docs/src/app/examples/data-table/selectable-rows/selectable-rows.component.ts
apps/docs/src/app/examples/menu/close-on-click/close-on-click.component.html
apps/docs/src/app/examples/menu/close-on-click/close-on-click.component.ts
apps/docs/src/assets/pages/components/checkbox.md
libs/anglify/src/components/checkbox/_variables.scss
libs/anglify/src/components/checkbox/checkbox.component.scss
libs/anglify/src/components/checkbox/checkbox.component.ts
libs/anglify/src/components/checkbox/interfaces/checkbox.interface.ts

feat(Checkbox): implemented indeterminate state

---

apps/docs-e2e/tsconfig.json
apps/docs/src/app/examples/dialog/complex/complex.component.html
apps/docs/src/app/examples/dialog/complex/complex.component.ts
apps/docs/src/assets/pages/components/dialog.md
apps/docs/tsconfig.json
libs/anglify/tsconfig.json

docs(Dialog): add detailed docs

---

apps/docs/src/app/components/code-example/code-example.component.html
apps/docs/src/app/components/code-example/code-example.component.ts
apps/docs/src/app/components/copy-button/copy-button.component.html
apps/docs/src/app/components/copy-button/copy-button.component.scss
apps/docs/src/app/components/copy-button/copy-button.component.ts
apps/docs/src/app/layouts/default/default.component.ts

docs: add copy code example button

---

libs/anglify/src/components/button/button.component.scss

fix(button): center loading state on block
